apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-manager
  template:
    metadata:
      labels:
        app: session-manager
    spec:
      serviceAccountName: session-manager-sa
      containers:
        - name: manager
          image: asia-south1-docker.pkg.dev/first-cedar-470107-j2/session-manager/session-manager:v2.0-webrtc
          volumeMounts:
            - name: templates
              mountPath: /app/templates
              readOnly: true
          ports:
            - containerPort: 80
          env:
            - name: LIVEKIT_URL
              valueFrom:
                secretKeyRef:
                  name: livekit-credentials
                  key: LIVEKIT_URL
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: livekit-credentials
                  key: LIVEKIT_API_KEY
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: livekit-credentials
                  key: LIVEKIT_API_SECRET
            - name: SESSION_BUBBLE_IMAGE_TAG
              value: "v2.0-webrtc"
      volumes:
        - name: templates
          configMap:
            name: session-manager-templates
