apiVersion: v1
kind: ServiceAccount
metadata:
  name: session-manager-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: session-manager-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete", "get"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "delete", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: session-manager-binding
subjects:
  - kind: ServiceAccount
    name: session-manager-sa
roleRef:
  kind: Role
  name: session-manager-role
  apiGroup: rbac.authorization.k8s.io
