apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{SESSION_ID}}
  annotations:
    networking.gke.io/pre-shared-certs: "session-bubble-wildcard"
    kubernetes.io/ingress.allow-http: "false"
    cloud.google.com/backend-config: '{"ports": {"command-ws":"session-bubble-backendconfig", "vnc-stream":"vnc-stream-backendconfig"}}'
spec:
  tls:
    - hosts:
        - {{SESSION_ID}}.vnc.shodh.ai
      secretName: ingress-tls-placeholder
  rules:
    - host: {{SESSION_ID}}.vnc.shodh.ai
      http:
        paths:
          - path: /stream
            pathType: Prefix
            backend:
              service:
                name: service-{{SESSION_ID}}
                port:
                  name: vnc-stream
          - path: /command
            pathType: Prefix
            backend:
              service:
                name: service-{{SESSION_ID}}
                port:
                  name: command-ws
